version: "3.7"
services:
  backend:
    container_name: backend
    hostname: backend
    build: ./backend
    ports:
      - "4001:4001"
    depends_on:
      - db
    networks:
      - network
  db:
    build: ./mysql
    container_name: db
    hostname: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_ROOT_HOST: "%"
    volumes:
      - "mysql-data:/var/lib/mysql"
    networks:
      - network
  frontend:
    container_name: frontend
    hostname: frontend
    build: ./frontend
    ports:
      - "4000:3000"
volumes:
  mysql-data:
networks:
  network:
